# db-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: 047719630685.dkr.ecr.us-east-1.amazonaws.com/db-image:latest
        command: [ "sh", "-c", "sleep 2000" ]
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: userdb
        ports:
        - containerPort: 3306
